### ISSUE TITLE
Не читает.

### ISSUE THREAD

**Issue by delvin-fil** [zvezdochiot/rhvoicebookreader#1]
**$ file test.txt** 
test.txt: UTF-8 Unicode text
**$ cat test.txt** 
Ничего не понимаю

**$ ./rhvoiceplay.sh test.txt** 
RHVoicePlay 0.20190517
gzip: skipping: test.txt unrecognized format
test.txt: 0
gzip: skipping: test.txt unrecognized format

Как с этим бороться?

**Comment by zvezdochiot** [comment]
@delvin-fil say> gzip: skipping: test.txt unrecognized format

Хмм. Такое поведение ```zcat``` я вижу впервые, похоже используется ссылка на ```gzip```.

Попробуйте заменить:

https://github.com/BASH-Auto-Tools/rhvoicebookreader/blob/de2108ee4b99703f75714cb5222009eeb50c8c89/rhvoiceplay.sh#L70

 на:
```
    gzip -dcf "$text" | sed -e 's/[\.\?\!\…] /&\n/g' | sed -e '/^$/d' | sed -e "1,${tln}d" | while read tline; do p=$((10000*$i/$textsize)); p1=$(($p/100)); p2=$(($p-$p1*100)); printf "%02d.%02d: " $p1 $p2; echo "$tline"; echo "$tline" | $trhvoice 2>/dev/null | $tplay - 2>/dev/null; i=$(($i+1)); done
```

**Comment by delvin-fil** [comment]
@zvezdochiot 
А текст обязательно болжен быть в архиве? И zcat и gzip, разумеется, установлены, но реакции никакой. Может быть текст должен быть не одной строкой?
```
./rhvoiceplay.sh test.txt 
RHVoicePlay 0.20190517
gzip: skipping: test.txt unrecognized format
test.txt: 0
```

Дал больше текста иполучил:
```
./rhvoiceplay.sh test.txt 
RHVoicePlay 0.20190517
gzip: skipping: test.txt unrecognized format
test.txt: 0
./rhvoiceplay.sh: строка 70: 10000*0/0: деление на 0 (неверный маркер «0»)
```

**Comment by zvezdochiot** [comment]
@delvin-fil say> А текст обязательно болжен быть в архиве?

В том то и дело что нет, и ```zcat``` и ```gzip -dcf``` должны просто пропускать сквозь себя текст как есть и декодировать только ```gz```.

Дайте вывод:
```sh
$ zcat test.txt
$ gizp -dcf test.txt
```

**Comment by zvezdochiot** [comment]
@delvin-fil say> ./rhvoiceplay.sh: строка 70: 10000*0/0: деление на 0 (неверный маркер «0»)

Ах да. Забыл про ещё одну замену:
https://github.com/BASH-Auto-Tools/rhvoicebookreader/blob/de2108ee4b99703f75714cb5222009eeb50c8c89/rhvoiceplay.sh#L66
на:
```sh
textsize=$(gzip -dcf "$text" | sed -e 's/[\.\?\!\…] /&\n/g' | sed -e '/^$/d' | wc -l)
```

**Comment by delvin-fil** [comment]
@zvezdochiot 
gzip пропускает
```
gzip -dcf test.txt
Году эдак в 2003 может  1 год играли мы...
```
А вот zcat почему то нет.
```
zcat test.txt
gzip: skipping: test.txt unrecognized format
```
UPD:
@zvezdochiot say> Ах да. Забыл про ещё одну замену
Таки, да, заработало, **спасибо**
```
./rhvoiceplay.sh test.txt 
RHVoicePlay 0.20190517
test.txt: 6
00.00: Бродишь по лесу в растениях/деревьях/камнях находишь ????фей-духов?????
16.66: вызываешь на дуэль.
33.33: если выигрываешь - это фей достается тебе.
50.00: Вот собственно все что помнится, уже года два периодически ищу и ее могу найти.
66.66: Может кто помнит/знает?
```
Но голос alexander это что-то. Елену предпочитаю. Почему то у нее лучше с заглавными и знаками препинания.

**Comment by zvezdochiot** [comment]
@delvin-fil say> Елену предпочитаю. 

Полностью того же мнения. Наверное вместе с фиксом сменю ```default```.

**Comment by delvin-fil** [comment]
@zvezdochiot
Да, кстати, не знаете почему "чистый" RHVoice-test периодически недочитывает? Понимаю, впорос не к Вам. Но очень интересно Ваше мнение.

**Comment by zvezdochiot** [comment]
@delvin-fil say> почему "чистый" RHVoice-test периодически недочитывает?

Скорее всего неправильно определяет конец строки в ходе генерации (т.е. внутри процесса). Хотя может быть закрадывается ```EOF``` на котором "труба" обравается.

**Comment by delvin-fil** [comment]
@zvezdochiot 
> неправильно определяет конец строки в ходе генерации

Неа, рвет чтение в произвольном месте. При этом, с опцией вывода в wav дочитывет четко(проверял с дусяток раз). Я грешу на то, что кто-то использует ALSA и мешает дочитать.

**Comment by zvezdochiot** [comment]
@delvin-fil say>  с опцией вывода в wav дочитывет четко

Рвёт "трубу" ```EOF```. Почему посреди потока генерится ```EOF``` и как с этим бороться? Не знаю.

**Comment by delvin-fil** [comment]
offtop
Извините, а у вас есть аккаунт в какой нибудь соцсети? А то на другие темы, как то, pygame, пообщаться интересно.

**Comment by zvezdochiot** [comment]
@delvin-fil say> аккаунт в какой нибудь соцсети?

Я противник соцсетей. Даже на ЛОРе удалился. (Слишком много спама и троллинга).

**Comment by delvin-fil** [comment]
> Почему посреди потока генерится `EOF`

Вот и я не понял. Ни и ладно. Ещераз спасибо за помощь. Попробую сейчас мегабайтную текстуху скормить

> Я противник соцсетей.

Жаль. У меня есть небольшой [проект](https://github.com/delvin-fil/ADB-control-GUI), немного доработал и хочу обновить репозиторий. Хотелось бы услышать о моих косяках в использовании библиотеки.

**Comment by zvezdochiot** [comment]
@delvin-fil say> Попробую сейчас мегабайтную текстуху скормить

Тогда вопрос: Может заменить 100 процентов на 1000 промилей для начальной позиции чтения? (параметр ```-l```)

**Comment by delvin-fil** [comment]
> 100 процентов на 1000 промилей для начальной позиции чтения

Эммм? "промилей"?

**Comment by zvezdochiot** [comment]
Процент - сотая часть текста.
Промиля - тысячная часть текста.

**Comment by delvin-fil** [comment]
> параметр `-l`

Понял. Ну незнаю. Попробую.
А почему нельзя прервать чтение по ctrl+c? Останавливает чтение обзаца и начинает следующий.

**Comment by zvezdochiot** [comment]
@delvin-fil say> А почему нельзя прервать чтение по ctrl+c?

Не должно быть такого. Может несколько раз нужно сделать ```Ctrl+C```, чтобы оборвать цикл ```while```, но останов должен работать.

**Comment by delvin-fil** [comment]
```
./rhvoiceplay.sh test.txt 
RHVoicePlay 0.20190517
test.txt: 6
00.00: Бродишь по лесу в растениях/деревьях/камнях находишь ????фей-духов?????
16.66: вызываешь на дуэль.
^C33.33: если выигрываешь - это фей достается тебе.
^C50.00: Вот собственно все что помнится, уже года два периодически ищу и ее могу найти.
^C66.66: Может кто помнит/знает?

```

**^C** попытка оборвать.

**Comment by zvezdochiot** [comment]
УМВР.

```sh
$ rhvoiceplay Головачёв_ВВ-Реликт-1-Непредвиденные_встречи-Сжатая_пружина-1979.txt.gz 
RHVoicePlay 0.20190517
Головачёв_ВВ-Реликт-1-Непредвиденные_встречи-Сжатая_пружина-1979.txt.gz: 3270
00.00: РЕЛИКТ.
00.03: Книга I
00.06: НЕПРЕДВИДЕННЫЕ ВСТРЕЧИ
^C
```
ХЗ.

**Comment by delvin-fil** [comment]
> txt.gz

Сейчас попробую упаковать текст

**Comment by zvezdochiot** [comment]
@delvin-fil say> Сейчас попробую упаковать текст

Упаковка здесь не при чём. Это как то связано с настройками среды (терминала). Но я с таким не сталкивался. У меня ```Ctrl+C``` не срабатывает на очень "особых" тулзах и очень редко.

**Comment by zvezdochiot** [comment]
На крайний случай:
```sh
$ killall rhvoiceplay.sh
```

**Comment by delvin-fil** [comment]
> связано с настройками среды

Я так пониаю, у вас **dash**? У меня bash.

> killall rhvoiceplay.sh

Знаю. :)

**Comment by zvezdochiot** [comment]
@delvin-fil say> У меня bash.

Аналогично. Тока ```LXTerminal 0.1.11```.

**Comment by delvin-fil** [comment]
> LXTerminal

Tilda и Terminoligy

**Comment by zvezdochiot** [comment]
@delvin-fil say> нельзя прервать чтение

Попробую забиндить клавишу ```q```. Но это надо в манах ковыряться, так что не скоро будет. Сначала фикс, потом всё остальное

**Comment by delvin-fil** [comment]
> Попробую забиндить клавишу `q`

На питоне бы попробовал, с башскриптом не очень дружу.
