### ISSUE TITLE
Ctrl+C

### ISSUE THREAD

**Issue by zvezdochiot** [zvezdochiot/rhvoicebookreader#2]
https://github.com/BASH-Auto-Tools/rhvoicebookreader/issues/1#issuecomment-533774144

@delvin-fil, если добавить в начало скрипта:
```sh
trap "exit 0" SIGINT
```
поведение не изменится?

**Comment by delvin-fil** [comment]
И с 
```shell
trap "exit 0" SIGINT
```
не помогает

**Comment by delvin-fil** [comment]
"Бьет" с третего раза в этом тексте
```script
 ./rhvoiceplay.sh test.txt 
RHVoicePlay 0.20190517
test.txt: 4
00.00: Упаковка здесь не при чём.
^C25.00: Это как то связано с настройками среды (терминала).
^C50.00: Но я с таким не сталкивался.
$ 
```

**Comment by zvezdochiot** [comment]
А если поменять интерпретатор:
https://github.com/BASH-Auto-Tools/rhvoicebookreader/blob/744ce5facf846c5bb0f1f04768310efb85710997/rhvoiceplay.sh#L1
на:
```sh
#!/bin/bash
```
?

**Comment by delvin-fil** [comment]
> ```shell
> #!/bin/bash
> ```
Сразу сделал.
